#
# Module manifest for module 'proofpoint.tap'
#
# Generated by: bchap1n
# Generated on: 5/22/2022
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'proofpoint.tap.psm1'

    # Version number of this module.
    ModuleVersion        = '0.1.1'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID                 = '34ee4c03-1d8c-472d-a8dd-05e928e779b3'

    # Author of this module
    Author               = 'Brock Chapin'

    # Copyright statement for this module
    Copyright            = '(c) 2022 Brock Chapin. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'proofpoint TAP integration tools'

    RequiredModules      = @()
    PowershellVersion    = '7.2'
    FunctionsToExport    = @('Get-TAPclickers1hour','Get-TapClickersbyLookbackDays','Get-TapClickersToday')
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags         = 'Proofpoint'
            ProjectUri   = 'https://github.com/bchap1n/Proofpoint.TAP'
            LicenseUri   = 'https://github.com/bchap1n/Proofpoint.TAP/blob/main/LICENSE'
            IconUri      = ''
            Prerelease   = 'beta0005'
            ReleaseNotes = '## [0.1.1-beta0005] - 2022-06-02
### Minor Updates and Bug Fixes
- 👷 config for gitversion (07afd1e)
- 📝 docs''n''links (cf99dcc)

### Other
- ✅ add a useful pester test. don''t need nupkg anymore since in gallery, no idea how that 8fdea0f got in there (8fdea0f)
- a bit weird. I''m including the BuildOutput generated by Press and going to try and use the Github Action \ publish.ps1 to publish the built module. I have not figured out how to make Press and Actions play together. so I am doing the press build locally with the devcontainer (0f29dc4)
- tap doesn''t require psframework, thats for the build system. nupkg may be useful (5263733)
- initial commit (4c11c0b)'
        }
    }
}