#
# Module manifest for module 'proofpoint.tap'
#
# Generated by: bchap1n
# Generated on: 5/22/2022
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'proofpoint.tap.psm1'

    # Version number of this module.
    ModuleVersion        = '0.1.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID                 = '34ee4c03-1d8c-472d-a8dd-05e928e779b3'

    # Author of this module
    Author               = 'Brock Chapin'

    # Copyright statement for this module
    Copyright            = '(c) 2022 Brock Chapin. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'proofpoint TAP integration tools'

    RequiredModules      = @()
    PowershellVersion    = '7.2'
    FunctionsToExport    = @('Get-TAPclickers1hour','Get-TapClickersbyLookbackDays','Get-TapClickersToday')
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags         = 'Proofpoint'
            ProjectUri   = 'https://github.com/bchap1n/Proofpoint.TAP'
            LicenseUri   = 'https://github.com/bchap1n/Proofpoint.TAP/blob/main/LICENSE'
            IconUri      = ''
            Prerelease   = 'beta0001'
            ReleaseNotes = '## [0.1.0-beta0001] - 2022-06-01
### Other
- tap doesn''t require psframework, thats for the build system. nupkg may be useful (5263733)
- initial commit (4c11c0b)'
        }
    }
}



